[package]
name = "material-colors"
version = "0.5.0"
edition = "2024"
description = "Up-to-date material-color-utilities port"
documentation = "https://docs.rs/material-colors"
homepage = "https://github.com/Aiving/material-colors"
repository = "https://github.com/Aiving/material-colors.git"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["no_std", "palette", "color-scheme", "material-you"]
categories = ["graphics", "no-std"]

[dependencies]
ahash = { version = "0.8", default-features = false, optional = true }
indexmap = { version = "2.13", default-features = false, optional = true }
serde = { version = "1.0", default-features = false, features = [
    "derive",
], optional = true }
libm = { version = "0.2", optional = true }

[features]
default = ["std"]
alloc = []
std = ["alloc", "indexmap?/std", "serde?/std", "ahash?/std", "ahash?/runtime-rng"]
quantize = ["alloc", "dep:ahash", "indexmap"]
serde = ["dep:serde"]
libm = ["dep:libm"]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[dev-dependencies]
float-cmp = "0.10"
reqwest = "0.13"
tokio = { version = "1.52", features = ["rt", "macros"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
