#![allow(clippy::too_many_arguments)]
use core::{array::IntoIter, fmt};

use crate::{color::Rgb, dynamic_color::DynamicScheme};

pub mod variant;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Scheme {
    pub primary: Rgb,
    pub on_primary: Rgb,
    pub primary_container: Rgb,
    pub on_primary_container: Rgb,
    pub inverse_primary: Rgb,
    pub primary_fixed: Rgb,
    pub primary_fixed_dim: Rgb,
    pub on_primary_fixed: Rgb,
    pub on_primary_fixed_variant: Rgb,
    pub secondary: Rgb,
    pub on_secondary: Rgb,
    pub secondary_container: Rgb,
    pub on_secondary_container: Rgb,
    pub secondary_fixed: Rgb,
    pub secondary_fixed_dim: Rgb,
    pub on_secondary_fixed: Rgb,
    pub on_secondary_fixed_variant: Rgb,
    pub tertiary: Rgb,
    pub on_tertiary: Rgb,
    pub tertiary_container: Rgb,
    pub on_tertiary_container: Rgb,
    pub tertiary_fixed: Rgb,
    pub tertiary_fixed_dim: Rgb,
    pub on_tertiary_fixed: Rgb,
    pub on_tertiary_fixed_variant: Rgb,
    pub error: Rgb,
    pub on_error: Rgb,
    pub error_container: Rgb,
    pub on_error_container: Rgb,
    pub surface_dim: Rgb,
    pub surface: Rgb,
    pub surface_tint: Rgb,
    pub surface_bright: Rgb,
    pub surface_container_lowest: Rgb,
    pub surface_container_low: Rgb,
    pub surface_container: Rgb,
    pub surface_container_high: Rgb,
    pub surface_container_highest: Rgb,
    pub on_surface: Rgb,
    pub on_surface_variant: Rgb,
    pub outline: Rgb,
    pub outline_variant: Rgb,
    pub inverse_surface: Rgb,
    pub inverse_on_surface: Rgb,
    pub surface_variant: Rgb,
    pub background: Rgb,
    pub on_background: Rgb,
    pub shadow: Rgb,
    pub scrim: Rgb,
}

impl fmt::Display for Scheme {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(&self, f)
    }
}

impl Scheme {
    pub const fn new(
        primary: Rgb,
        on_primary: Rgb,
        primary_container: Rgb,
        on_primary_container: Rgb,
        inverse_primary: Rgb,
        primary_fixed: Rgb,
        primary_fixed_dim: Rgb,
        on_primary_fixed: Rgb,
        on_primary_fixed_variant: Rgb,
        secondary: Rgb,
        on_secondary: Rgb,
        secondary_container: Rgb,
        on_secondary_container: Rgb,
        secondary_fixed: Rgb,
        secondary_fixed_dim: Rgb,
        on_secondary_fixed: Rgb,
        on_secondary_fixed_variant: Rgb,
        tertiary: Rgb,
        on_tertiary: Rgb,
        tertiary_container: Rgb,
        on_tertiary_container: Rgb,
        tertiary_fixed: Rgb,
        tertiary_fixed_dim: Rgb,
        on_tertiary_fixed: Rgb,
        on_tertiary_fixed_variant: Rgb,
        error: Rgb,
        on_error: Rgb,
        error_container: Rgb,
        on_error_container: Rgb,
        surface_dim: Rgb,
        surface: Rgb,
        surface_tint: Rgb,
        surface_bright: Rgb,
        surface_container_lowest: Rgb,
        surface_container_low: Rgb,
        surface_container: Rgb,
        surface_container_high: Rgb,
        surface_container_highest: Rgb,
        on_surface: Rgb,
        on_surface_variant: Rgb,
        outline: Rgb,
        outline_variant: Rgb,
        inverse_surface: Rgb,
        inverse_on_surface: Rgb,
        surface_variant: Rgb,
        background: Rgb,
        on_background: Rgb,
        shadow: Rgb,
        scrim: Rgb,
    ) -> Self {
        Self {
            primary,
            on_primary,
            primary_container,
            on_primary_container,
            inverse_primary,
            primary_fixed,
            primary_fixed_dim,
            on_primary_fixed,
            on_primary_fixed_variant,
            secondary,
            on_secondary,
            secondary_container,
            on_secondary_container,
            secondary_fixed,
            secondary_fixed_dim,
            on_secondary_fixed,
            on_secondary_fixed_variant,
            tertiary,
            on_tertiary,
            tertiary_container,
            on_tertiary_container,
            tertiary_fixed,
            tertiary_fixed_dim,
            on_tertiary_fixed,
            on_tertiary_fixed_variant,
            error,
            on_error,
            error_container,
            on_error_container,
            surface_dim,
            surface,
            surface_tint,
            surface_bright,
            surface_container_lowest,
            surface_container_low,
            surface_container,
            surface_container_high,
            surface_container_highest,
            on_surface,
            on_surface_variant,
            outline,
            outline_variant,
            inverse_surface,
            inverse_on_surface,
            surface_variant,
            background,
            on_background,
            shadow,
            scrim,
        }
    }
}

impl From<DynamicScheme> for Scheme {
    fn from(scheme: DynamicScheme) -> Self {
        Self::new(
            scheme.primary(),
            scheme.on_primary(),
            scheme.primary_container(),
            scheme.on_primary_container(),
            scheme.inverse_primary(),
            scheme.primary_fixed(),
            scheme.primary_fixed_dim(),
            scheme.on_primary_fixed(),
            scheme.on_primary_fixed_variant(),
            scheme.secondary(),
            scheme.on_secondary(),
            scheme.secondary_container(),
            scheme.on_secondary_container(),
            scheme.secondary_fixed(),
            scheme.secondary_fixed_dim(),
            scheme.on_secondary_fixed(),
            scheme.on_secondary_fixed_variant(),
            scheme.tertiary(),
            scheme.on_tertiary(),
            scheme.tertiary_container(),
            scheme.on_tertiary_container(),
            scheme.tertiary_fixed(),
            scheme.tertiary_fixed_dim(),
            scheme.on_tertiary_fixed(),
            scheme.on_tertiary_fixed_variant(),
            scheme.error(),
            scheme.on_error(),
            scheme.error_container(),
            scheme.on_error_container(),
            scheme.surface_dim(),
            scheme.surface(),
            scheme.surface_tint(),
            scheme.surface_bright(),
            scheme.surface_container_lowest(),
            scheme.surface_container_low(),
            scheme.surface_container(),
            scheme.surface_container_high(),
            scheme.surface_container_highest(),
            scheme.on_surface(),
            scheme.on_surface_variant(),
            scheme.outline(),
            scheme.outline_variant(),
            scheme.inverse_surface(),
            scheme.inverse_on_surface(),
            scheme.surface_variant(),
            scheme.background(),
            scheme.on_background(),
            scheme.shadow(),
            scheme.scrim(),
        )
    }
}

impl IntoIterator for Scheme {
    type IntoIter = IntoIter<(&'static str, Rgb), 49>;
    type Item = (&'static str, Rgb);

    fn into_iter(self) -> Self::IntoIter {
        [
            ("primary", self.primary),
            ("on_primary", self.on_primary),
            ("primary_container", self.primary_container),
            ("on_primary_container", self.on_primary_container),
            ("inverse_primary", self.inverse_primary),
            ("primary_fixed", self.primary_fixed),
            ("primary_fixed_dim", self.primary_fixed_dim),
            ("on_primary_fixed", self.on_primary_fixed),
            ("on_primary_fixed_variant", self.on_primary_fixed_variant),
            ("secondary", self.secondary),
            ("on_secondary", self.on_secondary),
            ("secondary_container", self.secondary_container),
            ("on_secondary_container", self.on_secondary_container),
            ("secondary_fixed", self.secondary_fixed),
            ("secondary_fixed_dim", self.secondary_fixed_dim),
            ("on_secondary_fixed", self.on_secondary_fixed),
            ("on_secondary_fixed_variant", self.on_secondary_fixed_variant),
            ("tertiary", self.tertiary),
            ("on_tertiary", self.on_tertiary),
            ("tertiary_container", self.tertiary_container),
            ("on_tertiary_container", self.on_tertiary_container),
            ("tertiary_fixed", self.tertiary_fixed),
            ("tertiary_fixed_dim", self.tertiary_fixed_dim),
            ("on_tertiary_fixed", self.on_tertiary_fixed),
            ("on_tertiary_fixed_variant", self.on_tertiary_fixed_variant),
            ("error", self.error),
            ("on_error", self.on_error),
            ("error_container", self.error_container),
            ("on_error_container", self.on_error_container),
            ("surface_dim", self.surface_dim),
            ("surface", self.surface),
            ("surface_tint", self.surface_tint),
            ("surface_bright", self.surface_bright),
            ("surface_container_lowest", self.surface_container_lowest),
            ("surface_container_low", self.surface_container_low),
            ("surface_container", self.surface_container),
            ("surface_container_high", self.surface_container_high),
            ("surface_container_highest", self.surface_container_highest),
            ("on_surface", self.on_surface),
            ("on_surface_variant", self.on_surface_variant),
            ("outline", self.outline),
            ("outline_variant", self.outline_variant),
            ("inverse_surface", self.inverse_surface),
            ("inverse_on_surface", self.inverse_on_surface),
            ("surface_variant", self.surface_variant),
            ("background", self.background),
            ("on_background", self.on_background),
            ("shadow", self.shadow),
            ("scrim", self.scrim),
        ]
        .into_iter()
    }
}
