name: CI

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo clippy --all-targets -F image,serde -- -D warnings
    - name: rustfmt
      run: cargo fmt --all --check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - uses: Swatinem/rust-cache@v2
    - name: Run tests
      run: cargo test --all-targets -F image,serde
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt, rust-src
    - uses: Swatinem/rust-cache@v2
    - name: Build Documentation
      run: cargo doc --document-private-items -F image,serde --no-deps
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true


